# Generated by Django 4.1 on 2022-08-23 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('detalle', models.TextField()),
                ('modalidad', models.TextField()),
                ('lugar', models.CharField(max_length=200)),
                ('arancel', models.TextField()),
                ('imag', models.ImageField(blank=True, help_text='Seleccione una imagen para mostrar', null=True, upload_to='img/eventos')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ManyToManyField(related_name='evento', to='eventos_app.categoria')),
            ],
        ),
    ]
