# Generated by Django 4.1 on 2022-08-23 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='categorias',
            field=models.ManyToManyField(related_name='Evento', to='eventos_app.categoria'),
        ),
    ]
