# Generated by Django 4.1 on 2022-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0002_alter_evento_categorias'),
    ]

    operations = [
        migrations.CreateModel(
            name='modalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameField(
            model_name='evento',
            old_name='arancel',
            new_name='ingreso',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='modalidad',
        ),
        migrations.AddField(
            model_name='evento',
            name='modalidades',
            field=models.ManyToManyField(related_name='Evento', to='eventos_app.modalidad'),
        ),
    ]
