# Generated by Django 4.1 on 2022-08-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0003_modalidad_rename_arancel_evento_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='modalidades',
        ),
        migrations.AddField(
            model_name='evento',
            name='modalidad',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Online'), (2, 'Presencial')], default=2),
        ),
        migrations.DeleteModel(
            name='modalidad',
        ),
    ]
