# Generated by Django 4.1 on 2022-08-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0004_remove_evento_modalidades_evento_modalidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='ingreso',
        ),
        migrations.AddField(
            model_name='evento',
            name='participación',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Gratuito'), (2, 'Arancelado')], default=1),
        ),
    ]
