# Generated by Django 4.1 on 2022-08-31 23:52

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0005_remove_evento_ingreso_evento_participación'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='participación',
            new_name='ingreso',
        ),
        migrations.AlterField(
            model_name='evento',
            name='detalle',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
